language: php
php:
  - "5.6"

cache:
  directories:
  - vendor

before_install:
  - npm install -g grunt-cli
before_script:
  - "gem install compass"
  - "php -S localhost:8001 -t web/ > access.log 2>&1 &"
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar"
  - "java -jar selenium-server-standalone-*.jar > selenium.log 2>&1 &"
  - sleep 5
  - composer install -o

script:
  - vendor/bin/behat

after_script:
  - cat access.log
  - cat selenium.log
env:
  global:
    # SPHERE_CLIENT_ID
    - secure: MEht7kleJ/K9/daNOjEpPNJnXxKyQZ36oEM8fImi612BoJmZp/uwjuKpqKscIyyLwXSpsr7c9w+V2CfSk3QI+NGLnhSNgjJWE2QXxzxD6OgM0gKFTDtBq//+k77Sx4UnQDi0pQPRZ1BrfBUqrxw4H07i53hXd/kmjZnknRcbODc=
    # SPHERE_CLIENT_SECRET
    - secure: Q4zRyFxLw/7YlHG/iWzyR7V7Srm8LsQ3UgMshckUyqefhzhF19GefoPJdPdALyLVEYQMG3O/U1aebbyt8Puy5jWWKKiwFaQA+mMXzpBFcvhutgxByqBXdIysIhGU65No+WbiCKlpL2WPNtYvE1cMSjFfn7IX8ThGkBxhJQcha38=
    # SPHERE_PROJECT
    - secure: CPj46vCtmLaxGKXycJW+PmNXloXu5ruOV/Qg1mA6tU83oPjlxHVrqMOlb87ykf6U8X6XXAjMrgR0q3gBepPJg3HZmJyeOsVhwSU/jhfN7L1lR7BrQrPdLutvhuC6Fgj+b2Ubzh7PIt7pR6AYZyMCv5ofajW9aBcC5D556WJsSjE=
notifications:
  hipchat:
    rooms:
      secure: S2g1T6N2gadmi+Dt3IjTkTrVRmPf0PG1pN5JXlB35RarQHs0GzBfhD1YT8Lm9keLc+XhM92rkEs7EyIrUtB+0x1O5A9bvPw0mDhtNhO6iPZDFajbZAPyA27vrA/JUMfEbigbuUkwxZggxYS5hnszDdvlwF97znwjT9G7fGZBU3+InxESq/Zt8g0AAqckQ434UlzsnyTmnUa6m8wU+zLEaTNJpF6XJ5DHDDiI7vv30Y7ZLWSLNOp8JVuGT9YEE1Q9CQ+UNvcDWYcr/B3Jr23b3NP5phDBg9T+mjJyflZyo/PClF1f3O+xIpTsx5xRApEmbCRafKIMJb46vTptaVdOf9GxCzGPC6/MKR6ngJGAyh1+jVPebJUTvSVW4QTkftC5XxjySDmBJ390ipZ9NT/+3zUIvSkZBH3597BJYqAJDdAj04jGobqPNOvab6Van8uEgjuhr/tL0qdfiehZIzOW0Kg7mj6b/HQlORMbMA/xbJrg190QmFt8KktSVhFhJ8J/YrxkepzaYbEOLKxpku9kpp4+J0sGXdI01T6mSTNeo6OFMFFiy327+3JJ4FuXAej8DH7T2bssn9LO4mAYhjGupnCjf4xSqN6/xg9tqGMq5UeHRh2JdwwnoMuhFp8j76tU/TPaKEA30+Ir9dfZgIz9hdOWpERvUyfUnXfc31FmsRo=
