language: php
php:
  - "5.6"
cache:
  directories:
  - vendor
before_install:
- npm install -g grunt-cli
before_script:
- composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
- gem install compass
- sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ $TRAVIS_PHP_VERSION != 'nightly' ] && [ `php-config --vernum` -ge 50500 ] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install -f apcu ; else echo 'extension="apc.so"' >> ./tests/apc.ini ; fi"
- sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ $TRAVIS_PHP_VERSION != 'nightly' ] ; then phpenv config-add ./tests/apc.ini; fi"
- php -S localhost:8001 -t web/ web/index.php > access.log 2>&1 &
- sh -e /etc/init.d/xvfb start
- export DISPLAY=:99.0
- wget http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
- java -jar selenium-server-standalone-*.jar > selenium.log 2>&1 &
- sleep 5
- composer install -o --ignore-platform-reqs
script:
- vendor/bin/behat
after_script:
- cat access.log
- cat selenium.log
env:
  global:
  # SPHERE_CLIENT_ID
  - secure: Dn/3lgPbKZET6GBYsbscPFbGThAQxG9FTQ1c/DeqlZEljZ3PbqCOkj2tqtP2JWzS3F/KOU7fwdJDA2wmZqYmXIj7+LLu8Y3agyYyl45WanxgRtkluw+OC3kr78ws8tI6kifKcxex8wc404tKr3FMhz9waoFtb09th4hpMcyvVoFSE1uHq7SOLOuwcAWpIS43QWjs6ENGWIm69b6C/HBLpEIurUTkHEs75jUiup7iwbPldAm/wZ+5UxryxbCO9Mo+kfM0nTN+O4daLPKxs8ZPoAdFlCOXyORWKCYgiffB5uuK4Kn4NKF97UfpcVYHgnSwWsqaePcpTVpd/J1SIjf0Xia0o6wZBkWng2kg+eSagnPVxmC6jW7+FJ/poBBVxlFleSQUEaQ5Yx+LvOWh37lP+5jiNmgtaMc/4rKU97zGZLsG8SQHLlBDtxeQ/pbVuevwxDSRB3i5vBoRYA6PgXtXnuLDV1MAW314eFkVaiQc0MJFi0pE8aabzKT/AlOfUkm0NMr+qvZsBMNrfw/1vNxsyxBbWrvrrrxHmM2a9UTvpjUwoMKxLTnB4+GS77jpGmUHWhdkqT0bNOPm6hmsgUupNumS/CjL7EVNE1k3EzqKbNxWrmG6lxT/9XJ19ZJUsfBRkbjQpW/CFWJ5yk2sAVDHKIgxen3qI7h5hmtByDE58Ns=
  # SPHERE_CLIENT_SECRET
  - secure: gM/2foj/pV+B2fqMv/d4eEZrBs4SuOrFzJeACpSo8ITBt8IMiDeWkeCJJ4kboXXzMrMjGA+tB/PLTKIYxmyTBmeJQYX2XFWpDrnhMpQTZkqwMAZNqCOZ8f1RRmyarjgNAoEk2cqH9V/NA3Ae6sNgaElYsS7B7CHxDvAki2/zTglpgKRuPsSm3hsmpbTfeSY8a3rUkUmHWDISWtWh3pwVJRGL3M3vkpGZYKA4NLNIjx8EuerAKbyDpjl2SafXF3mubOlDQXoXF3UYR8b3jxm9NC6jRUwSJrUIZZJEv4JtAy2t77G6zveZuF1XKoyF6rknnskEUigWR37aZTgI4dgrNKFpKFOWhY1+gG3kzqMH3TiXvxuP7M/9jokDQ3Zk3nDzroGqgDmCr+j4xXeDY5QiVn+VDDwg5dwRke5tzv5u+7uMvVBxq4hurLilJGevuEGZXk3mjGmFNW+BVn0zRUE8wL4elJAFwvVcJH36MRz6HvpAnWSWLHp3pIJuZ0dUs5oaO/wGO3N/+yIkXo5iz8KDZKTiEWlYk3kAmyB1dUjn+SY539i9yAopNoSvfoF1PWz4RJvzVvAQwFzliEclpH+QpR2CHjpwrvGXs26lw4Y9k9HRByYNlQy89JS3W/XkDB7nbekcD7ii9WSdh3gla1jRAsRBmYzUJyKG4zeQngag810=
  # SPHERE_PROJECT
  - secure: V9uE3uUisKuVhCIII0iq5u8oIYWZsXwNhs1qpvcNTzKEkLPVCcVM94a/oQZ9M/TkYS9Ut3V/qQ47zIqlRKigSKlB3obzQ0v9Zj2u9RzHRZWKCDKMK6a+Y1QGlzrf2g3jTc57WvRsMJqarmEIsFvhEmfcfU4dwwf+k6l8PVb9Wg+wrQs1zX/1WAgczqF2vIYcYEDzuR/YwSUQk8tnpH3v0rTCjoBJVzDXizc3lENUB8sxLyEwLqagaO5w2EPyUvQjMm4DFHIrdKj5Q3R0ysCD8zmpMORrYVF1JRoLlBGi1OA3BcVZ80R7qgjlMEbIgf2j3ndv1N8AM5kONxVxKLw0cicbTlU57tmC+iBIdTmPSQVZDsVrfpMpnoagXepLBo7CjH8Vx7mj67xRLsSOZig45ZGi+A4gK3lWqHP62GQ3yO7Gn0phokHWiLKnSCvNxUKRmCYBQvFJdUyBICxGdSsMqsZE1PckvICSEDzChL69fUm6C1S8uHYeveeuC2xFiurk0Dz20Mf3JfKYZGXtrKdLfKWvT0kmow5si5Vi3QPDvpjKxybaJt3PgQPDhwVCYZ9s8SZ6doM2PAxtZm0Inp8Q+uL7rxcYml77IVD13RONhWGcPWa6JgXOC6wQju8Lqu7JXwU+pw/xyB64qYZ/sVmHHEC+KU6jMcU4mUM5wy3ZjPM=
notifications:
  hipchat:
    rooms:
      secure: S2g1T6N2gadmi+Dt3IjTkTrVRmPf0PG1pN5JXlB35RarQHs0GzBfhD1YT8Lm9keLc+XhM92rkEs7EyIrUtB+0x1O5A9bvPw0mDhtNhO6iPZDFajbZAPyA27vrA/JUMfEbigbuUkwxZggxYS5hnszDdvlwF97znwjT9G7fGZBU3+InxESq/Zt8g0AAqckQ434UlzsnyTmnUa6m8wU+zLEaTNJpF6XJ5DHDDiI7vv30Y7ZLWSLNOp8JVuGT9YEE1Q9CQ+UNvcDWYcr/B3Jr23b3NP5phDBg9T+mjJyflZyo/PClF1f3O+xIpTsx5xRApEmbCRafKIMJb46vTptaVdOf9GxCzGPC6/MKR6ngJGAyh1+jVPebJUTvSVW4QTkftC5XxjySDmBJ390ipZ9NT/+3zUIvSkZBH3597BJYqAJDdAj04jGobqPNOvab6Van8uEgjuhr/tL0qdfiehZIzOW0Kg7mj6b/HQlORMbMA/xbJrg190QmFt8KktSVhFhJ8J/YrxkepzaYbEOLKxpku9kpp4+J0sGXdI01T6mSTNeo6OFMFFiy327+3JJ4FuXAej8DH7T2bssn9LO4mAYhjGupnCjf4xSqN6/xg9tqGMq5UeHRh2JdwwnoMuhFp8j76tU/TPaKEA30+Ir9dfZgIz9hdOWpERvUyfUnXfc31FmsRo=
