language: php
php:
  - "5.6"
cache:
  directories:
  - vendor
before_script:
- composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
- sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ $TRAVIS_PHP_VERSION != 'nightly' ] && [ `php-config --vernum` -ge 50500 ] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install -f apcu ; else echo 'extension="apc.so"' >> ./tests/apc.ini ; fi"
- sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ $TRAVIS_PHP_VERSION != 'nightly' ] ; then phpenv config-add ./tests/apc.ini; fi"
- php -S localhost:8001 -t web/ web/index.php > access.log 2>&1 &
- sh -e /etc/init.d/xvfb start
- export DISPLAY=:99.0
- wget http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
- java -jar selenium-server-standalone-*.jar > selenium.log 2>&1 &
- sleep 5
- composer install -o --ignore-platform-reqs
script:
- vendor/bin/behat
after_script:
- cat access.log
- cat selenium.log
env:
  global:
  # SPHERE_CLIENT_ID
  - secure: Vir8kGIpYfiUvDYb0Dgk6cgqyoHNZZFR8+hpOju9WnhPgnpWZxFMf/kF4pR5uZfGh5qwM6VD3iDZTii0cxi21X/prOJnQoLzHVpZFreQkeFGfq6MarElOfbLrN5wCsI06+DQVsIzIhzuJ+QBvuiTOgcd9euLuSWdYmdOu422fGj/YNWfGVQlTYQ0dXT10siMOdhZs5kT/pHNMKKG+JbqiFM6+NS3Y8ksZCrjx663oxzPNVceg2rugqoRedqA3l3dkNAoD2IVZKc+WDjY2lA3WhZAmdg1rjI8Bv5cDcGTprV167rp5YTTlAeJHe0GRHUnqT0zOdKhRx/tdFpDPreRXg7itA5ItCsmFXO6KbXcuzIJEkgOceH6i1oZ2tDB3FYNedddYryTcLIA7QCWwJVL/tbEyNrgZHxjdadlSJX+Re+705f9jLmCSn4NudbKagxOJp2Mjp3TOZ+gOxeyd90JNanv/2MfbEUFFt+soV/xkEPFnjL8UoMMLO5LvDc0cpK38xpYKFV/5KFQKmmSqiNKvuI8S86fSONVzrhrOjZber1KsNGOplQEkZWvtJZlpd49JRn+fyZ3t0gzyrzh79zUXszCmf+MgYttwGWPDfGPSw1tZUKdFdozc4l95sAYikjrlcQadnmdFf29pJY6t9N9yk3oI4x7CPtc5Ekhh9u1iSE=
  # SPHERE_CLIENT_SECRET
  - secure: kI6JArxMokx00/i3XGLDESq6Y7t8r9lEYnrmr4yCJduYjDGD3S6iMTigb7OT44gQimZRDzcZg9FLrTQAN1ii0I8M46fKeCr4rd0edc4TgRtWW85jR7v1MNUqKZKaa0qVbAH2yYMgipgkmyE1YPWLggrDj64jPNG/a1958u3I24o0qrq2TIFTqzMS0KOOfs2vCxSvsTpmj+4c6Iq4PqijBZlEFX3LxiW2XKzXmnw/14N75BieZH4RprFOaFBCrZl2IckQ1AcvDavEyFFMC4/ElkMBJfKHY6qa19WVAWzK9MIB1IyFaFDK0DqetoyUCo7nNaNpvjGWTFgv0O2yU68WnDobh8DckUle2PUScPa4kAlWPnDGh5Sp5UN9f8+yunVzt2qOA4mucRYFYHWxsimzEYMs4shYO8ks+54C5nn7XHk5aZCAEUrE8z6Z/WAsnRDKrFBAm7P4flan1v+0wFzruu/XC7oabFvn5irR9tdaO36eAt5b6yfHb3ZEEEV+pc/G6YHMNb6NEBH3xzufIxOuLD4u+eE2jRYPQr6BKvyBoknIIjHDH/7yTAag9eb9zqdvDbDONlpFfqjZ/VpfcHRDmiO9AAnLyhVsX5d627CC+tAZidEnVX/cF5igoZtDKnAxJ3zIPvgl3esUurdhzDnZXkxzO2gbGthT5qpWqV0DdDE=
  # SPHERE_PROJECT
  - secure: U6HixuMZX04MNYSuQzQRdmIKW8TY9MHca9c6v/xyvC97JREK1iGODW5RLFjW4fzvSAUdtDwglfgrC+gblBBQ1O37YTXhVCTLYRtT35q5NcxG1W33N/HOxclcbYxh0MB2gECEH4BFei7xr721f7N9uLJjRxa0WVLiSYu9gSyHsjPv5p5JmfzjxtypFAlgsCUv7KbUz9od6eAm7scPbPhhBwpmyiHdnCYVoXsnA8O+DZfFaHf2QskjebT4VMPj4Pv6n3nMKxDQd+8eZBcIx8U2tco5Tidc34n0kpEfcK1qkxj6MpoJQy2IpiD9gLpYw72Ilho9moT2qmgEgftJE2zV2uJMjiMhNa0LcUh/Pr21UxnmQhx4oneqH5Pd+3wAKqqIFp1O4QluvkGWMzAOsy7XH3hnLkRh/wUvJleVBm/CMCW+gvocb15yKcYl4lah45IXuzadtcGrMeVdO7b73cHlAuXplkhvIOxBM6ud6h22YtEwX3BJhRJg601fj5o5AbiXl9RKshPIS9AF7ORUABw6m+xZpDqBk2hCEUn0Jbd7OY44oEVLAwtuvaVsM2TFJwImizhHSAr6hChvKIG01agdZGSP//z+zTTXLkExAU3azhAUETiqh1BfDU47tD5edBG0jWwqi43N+W2z3UNBQpqj5xpw7fgutf8v9/YskADAejE=
notifications:
  hipchat:
    rooms:
      secure: S2g1T6N2gadmi+Dt3IjTkTrVRmPf0PG1pN5JXlB35RarQHs0GzBfhD1YT8Lm9keLc+XhM92rkEs7EyIrUtB+0x1O5A9bvPw0mDhtNhO6iPZDFajbZAPyA27vrA/JUMfEbigbuUkwxZggxYS5hnszDdvlwF97znwjT9G7fGZBU3+InxESq/Zt8g0AAqckQ434UlzsnyTmnUa6m8wU+zLEaTNJpF6XJ5DHDDiI7vv30Y7ZLWSLNOp8JVuGT9YEE1Q9CQ+UNvcDWYcr/B3Jr23b3NP5phDBg9T+mjJyflZyo/PClF1f3O+xIpTsx5xRApEmbCRafKIMJb46vTptaVdOf9GxCzGPC6/MKR6ngJGAyh1+jVPebJUTvSVW4QTkftC5XxjySDmBJ390ipZ9NT/+3zUIvSkZBH3597BJYqAJDdAj04jGobqPNOvab6Van8uEgjuhr/tL0qdfiehZIzOW0Kg7mj6b/HQlORMbMA/xbJrg190QmFt8KktSVhFhJ8J/YrxkepzaYbEOLKxpku9kpp4+J0sGXdI01T6mSTNeo6OFMFFiy327+3JJ4FuXAej8DH7T2bssn9LO4mAYhjGupnCjf4xSqN6/xg9tqGMq5UeHRh2JdwwnoMuhFp8j76tU/TPaKEA30+Ir9dfZgIz9hdOWpERvUyfUnXfc31FmsRo=
