app:
  sunrise:
    assetsPath: '/assets/'
    sale:
      slug: 'sale'
    itemsPerPage:
    - 12
    - 24
    - 48
    cart:
      attributes:
      - color
      - size
    products:
      sort:
        new:
          formValue: new
          searchParam: createdAt desc
        price-asc:
          formValue: priceAsc
          searchParam: price asc
        price-desc:
          formValue: priceDesc
          searchParam: price desc
      variantsSelector:
        main:
        - color
        - size
      details:
        attributes:
          main:
          - designer
          - gender
          - style
      facets:
        color:
          attribute: color
        size:
          attribute: commonSize
        brand:
          attribute: designer
          display: list
  languages:
  - de
  - en
  countries:
  - DE
  - UK
  currencies:
    DE: EUR
    UK: GBP
  fallback_languages:
    de:
    - en
    en:
    - de
  cache:
    categories: true
    productTypes: true
    products: true
#  commercetools:
#    client_id: <client_id>
#    client_secret: <client_secret>
#    project: <project>
imports:
  - { resource: 'app.yaml', ignore_errors: true}
