imports:
  - { resource: 'parameters.yml' }
  - { resource: 'security.yml' }
  - { resource: 'services.yml' }
  - { resource: 'app.yml' }

framework:
  secret: "%secret%"
  templating:
    engines: ['twig', 'handlebars']
  assets:
    base_path: /assets/
  default_locale: en
  esi: { enabled: true }
  fragments: ~
  session:
    name: sunrise_session
    save_path: ~
  translator:
    paths:
    - %kernel.root_dir%/../vendor/commercetools/sunrise-design/translations
twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
handlebars:
  cache: %kernel.cache_dir%/handlebars
  paths:
    - %kernel.root_dir%/Resources/views
    - %kernel.root_dir%/../vendor/commercetools/sunrise-design/templates
  helpers:
    esi: JaySDe\HandlebarsBundle\HandlebarsHelper::esi
    i18n: JaySDe\HandlebarsBundle\HandlebarsHelper::trans
    json: JaySDe\HandlebarsBundle\HandlebarsHelper::json
