_home:
  path:      /
  defaults:  { _controller: app.catalog.controller:homeAction }
  methods:  [GET, HEAD]
home:
  path: /{_locale}/
  defaults:  { _controller: app.catalog.controller:homeAction }
  methods:  [GET, HEAD]
pop:
  path: /{_locale}/search/
  defaults:  { _controller: app.catalog.controller:searchAction }
  methods:  [GET, HEAD]
pdp-master:
  path: /{_locale}/{slug}.html
  defaults:  { _controller: app.catalog.controller:detailAction }
  methods:  [GET, HEAD]
pdp:
  path: /{_locale}/{slug}/{sku}.html
  defaults:  { _controller: app.catalog.controller:detailAction }
  methods:  [GET, HEAD]

myAccount:
  path: /{_locale}/user/details
  defaults:  { _controller: app.user.controller:detailsAction }
  methods:  [GET, HEAD]
myDetails:
  path: /{_locale}/user/details
  defaults:  { _controller: app.user.controller:detailsAction }
  methods:  [GET, HEAD, POST]
myAdressBook:
  path: /{_locale}/user/addresses
  defaults:  { _controller: app.user.controller:addressesAction }
  methods:  [GET, HEAD]
editAddress:
  path: /{_locale}/user/address/edit/{id}
  defaults:  { _controller: app.user.controller:editAddressAction }
  methods:  [GET, HEAD, POST]
myOrders:
  path: /{_locale}/user/orders
  defaults: { _controller: app.user.controller:ordersAction }
  methods:  [GET, HEAD]

myOrderDetails:
  path: /{_locale}/user/orders/{orderId}
  defaults: { _controller: app.user.controller:orderDetailAction }
  methods:  [GET, HEAD]

login_route:
  path: /{_locale}/login
  defaults:  { _controller: app.user.controller:loginAction }
  methods:  [GET, HEAD, POST]
login_check:
  path: /{_locale}/login_check

logout:
  path: /{_locale}/logout

checkout:
  path: /{_locale}/checkout
  defaults:  { _controller: app.cart.controller:checkoutAction }
  methods:  [GET, HEAD, POST]
checkoutSignin:
  path: /{_locale}/checkout/signin
  defaults:  { _controller: app.cart.controller:checkoutSigninAction }
  methods:  [GET, HEAD]
checkoutShipping:
  path: /{_locale}/checkout/shipping
  defaults:  { _controller: app.cart.controller:checkoutShippingAction }
  methods:  [GET, HEAD]
checkoutPayment:
  path: /{_locale}/checkout/payment
  defaults:  { _controller: app.cart.controller:checkoutPaymentAction }
  methods:  [GET, HEAD]
checkoutConfirmation:
  path: /{_locale}/checkout/confirmation
  defaults:  { _controller: app.cart.controller:checkoutConfirmationAction }
  methods:  [GET, HEAD]

cartAdd:
  path: /{_locale}/cart/add
  defaults:  { _controller: app.cart.controller:addAction }
  methods:  [POST]
lineItemDelete:
  path: /{_locale}/cart/delete
  defaults:  { _controller: app.cart.controller:deleteLineItemAction }
  methods:  [POST]
lineItemChange:
  path: /{_locale}/cart/change
  defaults:  { _controller: app.cart.controller:changeLineItemAction }
  methods:  [POST]
cart:
  path: /{_locale}/cart
  defaults:  { _controller: app.cart.controller:indexAction }
  methods:  [GET, HEAD]
miniCart:
  path: /{_locale}/cart/mini
  defaults:  { _controller: app.cart.controller:miniCartAction }
  methods:  [GET, HEAD]

category:
  path: /{_locale}/{category}/
  defaults:  { _controller: app.catalog.controller:searchAction }
  methods:  [GET, HEAD]

