security:
  providers:
    ctp:
      id: commercetools.user_provider
#    in_memory:
#      memory:
#        users:
#          ylambers:
#            password: yaron
#            roles: 'ROLE_USER'
  access_control:
  - { path: /user/, roles: ROLE_USER }
#  - { path: ^/{_locale}/user/details, roles: ROLE_USER }
#  - { path: user/addresses, roles: ROLE_USER }
#  - { path: user/address/edit, roles: ROLE_USER }
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Commercetools\Symfony\CtpBundle\Security\User\User: plaintext
  firewalls:
    main:
      anonymous: ~
      commercetools-login:
        login_path: login_route
        check_path: login_check
      logout:
        path:   logout
        target: home
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    default:
      anonymous: ~
